name: Build and Publish Docker Image

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main, master, dev ]
    tags: [ 'v*' ]
    paths-ignore:
      - 'README.md'
      - '**.md'
      - '.github/workflows/**'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required to push to GitHub Container Registry    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Generate version number
        id: version
        run: |
          # Generate date-based version
          DATE_TAG=$(date +'%Y%m%d')
          
          # Get commit count for additional uniqueness
          COMMIT_COUNT=$(git rev-list --count HEAD)
          
          # Create a version like 20250302.45 (date.commit_count)
          VERSION_TAG="${DATE_TAG}.${COMMIT_COUNT}"
          echo "VERSION=${VERSION_TAG}" >> $GITHUB_OUTPUT
          echo "DATE_TAG=${DATE_TAG}" >> $GITHUB_OUTPUT
          
          # Check if this is the dev branch
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "IS_DEV=true" >> $GITHUB_OUTPUT
          else
            echo "IS_DEV=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for Docker (Main branch)
        id: meta-main
        if: ${{ steps.version.outputs.IS_DEV == 'false' }}
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/traefik-dns-manager
            ghcr.io/${{ github.repository }}
          tags: |
            # Latest tag for main/master
            type=raw,value=latest,enable=true
            
            # Date + commit count for all builds
            type=raw,value=${{ steps.version.outputs.VERSION }}
            
            # Just date for all builds
            type=raw,value=${{ steps.version.outputs.DATE_TAG }}
      
      - name: Extract metadata for Docker (Dev branch)
        id: meta-dev
        if: ${{ steps.version.outputs.IS_DEV == 'true' }}
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/traefik-dns-manager
            ghcr.io/${{ github.repository }}
          tags: |
            # Dev tag
            type=raw,value=dev
            
            # Dev with version
            type=raw,value=dev-${{ steps.version.outputs.VERSION }}
      
      - name: Build and push Docker image (Main branch)
        if: ${{ steps.version.outputs.IS_DEV == 'false' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta-main.outputs.tags }}
          labels: ${{ steps.meta-main.outputs.labels }}
          cache-from: type=gha
      
      - name: Build and push Docker image (Dev branch)
        if: ${{ steps.version.outputs.IS_DEV == 'true' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta-dev.outputs.tags }}
          labels: ${{ steps.meta-dev.outputs.labels }}
          cache-from: type=gha
          # cache-to: type=gha,mode=max          