name: Build and Publish Docker Image

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
    paths-ignore:
      - 'README.md'
      - '**.md'
      - '.github/workflows/**'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required to push to GitHub Container Registry    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Generate version number
        id: version
        run: |
          # Generate date-based version
          DATE_TAG=$(date +'%Y%m%d')
          
          # Get commit count for additional uniqueness
          COMMIT_COUNT=$(git rev-list --count HEAD)
          
          # Create a version like 20250302.45 (date.commit_count)
          VERSION_TAG="${DATE_TAG}.${COMMIT_COUNT}"
          echo "VERSION=${VERSION_TAG}" >> $GITHUB_OUTPUT
          echo "DATE_TAG=${DATE_TAG}" >> $GITHUB_OUTPUT
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/traefik-dns-manager
            ghcr.io/${{ github.repository }}
          tags: |
            # Latest tag for main/master
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') || github.ref == format('refs/heads/{0}', 'master') }}
            
            # Date + commit count for all builds
            type=raw,value=${{ steps.version.outputs.VERSION }}
            
            # Just date for all builds
            type=raw,value=${{ steps.version.outputs.DATE_TAG }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          # cache-to: type=gha,mode=max