name: PR Verification

on:
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - 'README.md'
      - '**.md'

jobs:
  build-check:
    name: Docker Build Verification
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image for x64 only
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker-s6/Dockerfile
          platforms: linux/amd64
          push: false
          load: true  # Load the image for local verification
          tags: trafegodns:pr-check
          cache-from: type=gha
      
      - name: Verify image builds successfully
        run: |
          docker image inspect trafegodns:pr-check
          echo "✅ Docker image built successfully"
      
      - name: Verify multi-arch build process
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker-s6/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: false
          cache-from: type=gha
          outputs: type=image,name=trafegodns:pr-multiarch-check,push=false